export const statesOfMexico = [
  { name: "Aguascalientes", abbreviation: "AGS" },
  { name: "Baja California", abbreviation: "BC" },
  { name: "Baja California Sur", abbreviation: "BCS" },
  { name: "Campeche", abbreviation: "CAMP" },
  { name: "Chiapas", abbreviation: "CHIS" },
  { name: "Chihuahua", abbreviation: "CHIH" },
  { name: "Mexico City", abbreviation: "CDMX" },
  { name: "Coahuila", abbreviation: "COAH" },
  { name: "Colima", abbreviation: "COL" },
  { name: "Durango", abbreviation: "DGO" },
  { name: "State of Mexico", abbreviation: "MEX" },
  { name: "Guanajuato", abbreviation: "GTO" },
  { name: "Guerrero", abbreviation: "GRO" },
  { name: "Hidalgo", abbreviation: "HGO" },
  { name: "Jalisco", abbreviation: "JAL" },
  { name: "Michoacán", abbreviation: "MICH" },
  { name: "Morelos", abbreviation: "MOR" },
  { name: "Nayarit", abbreviation: "NAY" },
  { name: "Nuevo León", abbreviation: "NL" },
  { name: "Oaxaca", abbreviation: "OAX" },
  { name: "Puebla", abbreviation: "PUE" },
  { name: "Querétaro", abbreviation: "QRO" },
  { name: "Quintana Roo", abbreviation: "QR" },
  { name: "San Luis Potosí", abbreviation: "SLP" },
  { name: "Sinaloa", abbreviation: "SIN" },
  { name: "Sonora", abbreviation: "SON" },
  { name: "Tabasco", abbreviation: "TAB" },
  { name: "Tamaulipas", abbreviation: "TAMPS" },
  { name: "Tlaxcala", abbreviation: "TLAX" },
  { name: "Veracruz", abbreviation: "VER" },
  { name: "Yucatán", abbreviation: "YUC" },
  { name: "Zacatecas", abbreviation: "ZAC" },
];
